version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3

# jobs:
#   build:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Run build
#           command: npm run build
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .
workflows:
  test_my_app:
    jobs:
      - cypress/run: 
          install-browsers: true
          start-command: npm run start
          cypress-command: npx cypress run --browser chrome
      # - start-command: 

# version: 2.1
# orbs:
#   node: circleci/node@5.1.0
#   cypress: cypress-io/cypress@3.1.3

# jobs:
#   build:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Run build
#           command: npm run build
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .

# workflows:
#   test_my_app:
#     jobs:
#       - cypress/run:
#           command: npm run cy:run

